#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication ./Allmesh

#-- Run on single processor
#runApplication $(getApplication)

# Decompose
runApplication decomposePar -allRegions

# Run
runParallel $(getApplication)

# Reconstruct
## runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
