#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#- Run in multi-region mode
./Allrun.pre
runApplication $(getApplication)

#------------------------------------------------------------------------------
