#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

#------------------------------------------------------------------------------

wclean meshLibrary
wclean -all executables
wclean -all utilities

#------------------------------------------------------------------------------
