#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
targetType=libso
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

catalyst/Allwmake $targetType $*
paraview-plugins/Allwmake $targetType $*
runTimePostProcessing/Allwmake $targetType $*

#------------------------------------------------------------------------------
