#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions    # Tutorial run functions
#------------------------------------------------------------------------------

runApplication slopeMesh

runApplication makeFaMesh

# Restore initial fields
restore0Dir

runApplication releaseAreaMapping

runApplication $(getApplication)

#------------------------------------------------------------------------------
