#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

echo "wmake $targetType dummy (mpi=$WM_MPLIB)"
wmake $targetType dummy

./Allwmake-mpi $targetType $*

#------------------------------------------------------------------------------
