#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. "${WM_PROJECT_DIR:?}"/wmake/scripts/have_adios2
#------------------------------------------------------------------------------

if have_adios2
then
    adiosFoam/Allwmake
    adiosWrite/Allwmake
else
    hint_adios2
fi

# -----------------------------------------------------------------------------
