#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions    # Tutorial run functions
#------------------------------------------------------------------------------

runApplication slopeMesh

runApplication makeFaMesh

# Restore initial fields (prior to decompose)
restore0Dir

runApplication decomposePar

runParallel releaseAreaMapping

runParallel $(getApplication)

#------------------------------------------------------------------------------
